config/routes.rb
Rails.application.routes.draw do
  get 'cartoon/index'
  root "cartoon#index"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get 'cartoon/details'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cartoon.rb
class Cartoon
	include HTTParty

	base_uri 'rickandmortyapi.com/api'

	def self.allCharacters
		get('/character')
	end

	def self.search(name)
		get("/character/?name=#{name}")
	end

	def self.getMoreDetails(id)
		get("/character/#{id}")
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cartoon_controller.rb
class CartoonController < ApplicationController
	def index
		@search_term = params['search_term'] || 'rick'
		@cartoon = Cartoon.search(@search_term)
	end

	def details
		@cartoon = Cartoon.getMoreDetails(params[:id])
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cartoon_helper.rb
module CartoonHelper
end

app/views/cartoon/details.html.erb
<div class="table-responsive">
	<table class="table table-striped">
	<thead>
		<tr>
			<th scope="col">Character Image</th>
			<th scope="col">Character Id</th>
			<th scope="col">Character Name</th>
			<th scope="col">Character Status</th>
			<th scope="col">Character Species</th>
			<th scope="col">Character Gender</th>
			<th scope="col">Episodes appeared in</th>
			<th scope="col">Origin</th>
		</tr>
	</thead>
	<tbody>
		<tr>
			<td><%= image_tag @cartoon['image'] %></td>
			<td><%= @cartoon['id'] %></td>
			<td><%= @cartoon['name'] %></td>
			<td><%= @cartoon['status'] %></td>
			<td><%= @cartoon['species'] %></td>
			<td><%= @cartoon['gender'] %></td>
			<td><%= @cartoon['episode'] %></td>
			<td><%= @cartoon["origin"]['name'] %></td>
		</tr>
	</tbody>
	</table>
</div>

app/views/cartoon/index.html.erb
<h1>Rick and Morty API</h1>
<div>
	<h2>Base url: https://rickandmortyapi.com/api</h2>
	<p>The base url contains information about all available API's resources. All requests are GET requests and go over https. All responses will return data in json</p>
	<p>There are currently three available resources:</p>
	<ol>
		<li>Character: used to get all the characters.</li>
		<li>Location: used to get all the locations.</li>
		<li>Episode: used to get all the episodes.</li>
	</ol>
</div>
<div class="table-responsive">
	<table class="table table-striped">
		<thead>
			<tr>
				<th scope="col">Character Id</th>
				<th scope="col">Character Image</th>
				<th scope="col">Character Name</th>
				<th scope="col">Link to More Details about the character</th>
			</tr>
		</thead>
		<tbody>
			<% @cartoon["results"].each do |character| %>
			<tr class="<%= cycle('even', 'odd') %>">
				<td><%= character['id'] %></td>
				<td><%= image_tag character['image'] %></td>
				<td><%= character['name'] %></td>
				<td><%= link_to "More Details", cartoon_details_path(:id => character['id']) %></td>
			</tr>
			<% end %>
		</tbody>
	</table>	
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RickMorty</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="../../assets/stylesheets/cartoon.css">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="container">
      <div class="row">
        <%= yield %>
      </div>
    </div>
  </body>
</html>